name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * 1"   # раз в неделю, понедельник
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: VikkMoor

          # Куда сохраняем SVG
          filename: stats/github-metrics.svg

          # БАЗОВАЯ СТАТИСТИКА (аналог основной карточки)
          base: header, activity, repositories
          base_hireable: false

          # ЯЗЫКИ (аналог Top Langs)
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_threshold: 0%
          plugin_languages_details: percentage
          plugin_languages_colors: github
          plugin_languages_indepth: true
          plugin_languages_layout: compact


          # ВНЕШНИЙ ВИД
          config_display: block
          config_padding: 0, 5%
          config_width: 700
          config_timezone: Europe/Moscow
          config_theme: dark
          

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add stats
          git commit -m "Update GitHub metrics" || exit 0
          git push
